export const MESSAGES: {
  [key: string]: { [key: string]: string };
} = {
  en: {
    method: "Method",
    headers: "Headers",
    addHeader: "+ Add header",
    options: "Options",
    auth: "Authentication",
    output: "File output",
    result: "Generated Command",
    body: "Request Body",
    optionIncludeHeaders: "Include response headers (-i)",
    optionVerbose: "Verbose output (-v)",
    optionFollowRedirects: "Follow redirects (-L)",
    optionInsecure: "Ignore SSL certificate verification (-k)",
    optionOutput: "Output to file (-o)",
    optionBasicAuth: "Basic Auth (-u)",
    optionBearerToken: "Use Bearer Token",
    placeholderUserName: "User Name",
    placeholderPassword: "Password",
    placeholderBearerToken: "Bearer Token",
    placeholderFileName: "File name (e.g., result.json)",
  },
  ja: {
    method: "メソッド",
    headers: "ヘッダー",
    addHeader: "+ ヘッダー追加",
    options: "オプション",
    auth: "認証",
    output: "ファイル出力",
    result: "生成されたコマンド",
    body: "リクエストボディ",
    optionIncludeHeaders: "ヘッダー表示 (-i)",
    optionVerbose: "詳細出力 (-v)",
    optionFollowRedirects: "リダイレクト追跡 (-L)",
    optionInsecure: "証明書検証無効 (-k)",
    optionOutput: "ファイル出力 (-o)",
    optionBasicAuth: "Basic認証 (-u)",
    optionBearerToken: "Bearerトークンを使用",
    placeholderUserName: "ユーザー名",
    placeholderPassword: "パスワード",
    placeholderBearerToken: "Bearer トークン",
    placeholderFileName: "ファイル名 (例: result.json)",
  },
};
